### ISSUE TITLE
响应式编程的第二个拼写错误

### ISSUE THREAD

**Issue by luoyjx** [jobbole/awesome-javascript-cn#5]
FPR => FRP

**Comment by liyunsong** [comment]
@luoyjx :+1: 我还是第一次知道这个词。。没怎么用过 github,是因为我star了才收到通知的吗

**Comment by luoyjx** [comment]
@liyunsong 
FRP (functional reactive programming)
https://github.com/baconjs/bacon.js 项目的描述有写这个词

**Comment by tangyouhua** [comment]
Thanks. 已更正
